/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ApproachRouteImport } from './routes/approach'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesIndexRouteImport } from './routes/services/index'
import { Route as CaseStudiesIndexRouteImport } from './routes/case-studies/index'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as ToolsRoiCalculatorRouteImport } from './routes/tools/roi-calculator'
import { Route as ToolsAiReadinessAssessmentRouteImport } from './routes/tools/ai-readiness-assessment'
import { Route as ServicesDigitalTransformationRouteImport } from './routes/services/digital-transformation'
import { Route as ServicesChatbotsRouteImport } from './routes/services/chatbots'
import { Route as ServicesAiToolsRouteImport } from './routes/services/ai-tools'
import { Route as ServicesAiConsultingRouteImport } from './routes/services/ai-consulting'
import { Route as ServicesAiAutomationRouteImport } from './routes/services/ai-automation'
import { Route as ServicesAiAgentsRouteImport } from './routes/services/ai-agents'
import { Route as CaseStudiesSlugRouteImport } from './routes/case-studies/$slug'
import { Route as BlogSlugRouteImport } from './routes/blog/$slug'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ApproachRoute = ApproachRouteImport.update({
  id: '/approach',
  path: '/approach',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseStudiesIndexRoute = CaseStudiesIndexRouteImport.update({
  id: '/case-studies/',
  path: '/case-studies/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsRoiCalculatorRoute = ToolsRoiCalculatorRouteImport.update({
  id: '/tools/roi-calculator',
  path: '/tools/roi-calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsAiReadinessAssessmentRoute =
  ToolsAiReadinessAssessmentRouteImport.update({
    id: '/tools/ai-readiness-assessment',
    path: '/tools/ai-readiness-assessment',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesDigitalTransformationRoute =
  ServicesDigitalTransformationRouteImport.update({
    id: '/services/digital-transformation',
    path: '/services/digital-transformation',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesChatbotsRoute = ServicesChatbotsRouteImport.update({
  id: '/services/chatbots',
  path: '/services/chatbots',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesAiToolsRoute = ServicesAiToolsRouteImport.update({
  id: '/services/ai-tools',
  path: '/services/ai-tools',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesAiConsultingRoute = ServicesAiConsultingRouteImport.update({
  id: '/services/ai-consulting',
  path: '/services/ai-consulting',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesAiAutomationRoute = ServicesAiAutomationRouteImport.update({
  id: '/services/ai-automation',
  path: '/services/ai-automation',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesAiAgentsRoute = ServicesAiAgentsRouteImport.update({
  id: '/services/ai-agents',
  path: '/services/ai-agents',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseStudiesSlugRoute = CaseStudiesSlugRouteImport.update({
  id: '/case-studies/$slug',
  path: '/case-studies/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/approach': typeof ApproachRoute
  '/contact': typeof ContactRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/resources': typeof ResourcesRoute
  '/terms': typeof TermsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/case-studies/$slug': typeof CaseStudiesSlugRoute
  '/services/ai-agents': typeof ServicesAiAgentsRoute
  '/services/ai-automation': typeof ServicesAiAutomationRoute
  '/services/ai-consulting': typeof ServicesAiConsultingRoute
  '/services/ai-tools': typeof ServicesAiToolsRoute
  '/services/chatbots': typeof ServicesChatbotsRoute
  '/services/digital-transformation': typeof ServicesDigitalTransformationRoute
  '/tools/ai-readiness-assessment': typeof ToolsAiReadinessAssessmentRoute
  '/tools/roi-calculator': typeof ToolsRoiCalculatorRoute
  '/blog/': typeof BlogIndexRoute
  '/case-studies/': typeof CaseStudiesIndexRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/approach': typeof ApproachRoute
  '/contact': typeof ContactRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/resources': typeof ResourcesRoute
  '/terms': typeof TermsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/case-studies/$slug': typeof CaseStudiesSlugRoute
  '/services/ai-agents': typeof ServicesAiAgentsRoute
  '/services/ai-automation': typeof ServicesAiAutomationRoute
  '/services/ai-consulting': typeof ServicesAiConsultingRoute
  '/services/ai-tools': typeof ServicesAiToolsRoute
  '/services/chatbots': typeof ServicesChatbotsRoute
  '/services/digital-transformation': typeof ServicesDigitalTransformationRoute
  '/tools/ai-readiness-assessment': typeof ToolsAiReadinessAssessmentRoute
  '/tools/roi-calculator': typeof ToolsRoiCalculatorRoute
  '/blog': typeof BlogIndexRoute
  '/case-studies': typeof CaseStudiesIndexRoute
  '/services': typeof ServicesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/approach': typeof ApproachRoute
  '/contact': typeof ContactRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/resources': typeof ResourcesRoute
  '/terms': typeof TermsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/case-studies/$slug': typeof CaseStudiesSlugRoute
  '/services/ai-agents': typeof ServicesAiAgentsRoute
  '/services/ai-automation': typeof ServicesAiAutomationRoute
  '/services/ai-consulting': typeof ServicesAiConsultingRoute
  '/services/ai-tools': typeof ServicesAiToolsRoute
  '/services/chatbots': typeof ServicesChatbotsRoute
  '/services/digital-transformation': typeof ServicesDigitalTransformationRoute
  '/tools/ai-readiness-assessment': typeof ToolsAiReadinessAssessmentRoute
  '/tools/roi-calculator': typeof ToolsRoiCalculatorRoute
  '/blog/': typeof BlogIndexRoute
  '/case-studies/': typeof CaseStudiesIndexRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/approach'
    | '/contact'
    | '/privacy-policy'
    | '/resources'
    | '/terms'
    | '/blog/$slug'
    | '/case-studies/$slug'
    | '/services/ai-agents'
    | '/services/ai-automation'
    | '/services/ai-consulting'
    | '/services/ai-tools'
    | '/services/chatbots'
    | '/services/digital-transformation'
    | '/tools/ai-readiness-assessment'
    | '/tools/roi-calculator'
    | '/blog/'
    | '/case-studies/'
    | '/services/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/approach'
    | '/contact'
    | '/privacy-policy'
    | '/resources'
    | '/terms'
    | '/blog/$slug'
    | '/case-studies/$slug'
    | '/services/ai-agents'
    | '/services/ai-automation'
    | '/services/ai-consulting'
    | '/services/ai-tools'
    | '/services/chatbots'
    | '/services/digital-transformation'
    | '/tools/ai-readiness-assessment'
    | '/tools/roi-calculator'
    | '/blog'
    | '/case-studies'
    | '/services'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/approach'
    | '/contact'
    | '/privacy-policy'
    | '/resources'
    | '/terms'
    | '/blog/$slug'
    | '/case-studies/$slug'
    | '/services/ai-agents'
    | '/services/ai-automation'
    | '/services/ai-consulting'
    | '/services/ai-tools'
    | '/services/chatbots'
    | '/services/digital-transformation'
    | '/tools/ai-readiness-assessment'
    | '/tools/roi-calculator'
    | '/blog/'
    | '/case-studies/'
    | '/services/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ApproachRoute: typeof ApproachRoute
  ContactRoute: typeof ContactRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  ResourcesRoute: typeof ResourcesRoute
  TermsRoute: typeof TermsRoute
  BlogSlugRoute: typeof BlogSlugRoute
  CaseStudiesSlugRoute: typeof CaseStudiesSlugRoute
  ServicesAiAgentsRoute: typeof ServicesAiAgentsRoute
  ServicesAiAutomationRoute: typeof ServicesAiAutomationRoute
  ServicesAiConsultingRoute: typeof ServicesAiConsultingRoute
  ServicesAiToolsRoute: typeof ServicesAiToolsRoute
  ServicesChatbotsRoute: typeof ServicesChatbotsRoute
  ServicesDigitalTransformationRoute: typeof ServicesDigitalTransformationRoute
  ToolsAiReadinessAssessmentRoute: typeof ToolsAiReadinessAssessmentRoute
  ToolsRoiCalculatorRoute: typeof ToolsRoiCalculatorRoute
  BlogIndexRoute: typeof BlogIndexRoute
  CaseStudiesIndexRoute: typeof CaseStudiesIndexRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/approach': {
      id: '/approach'
      path: '/approach'
      fullPath: '/approach'
      preLoaderRoute: typeof ApproachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case-studies/': {
      id: '/case-studies/'
      path: '/case-studies'
      fullPath: '/case-studies/'
      preLoaderRoute: typeof CaseStudiesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/roi-calculator': {
      id: '/tools/roi-calculator'
      path: '/tools/roi-calculator'
      fullPath: '/tools/roi-calculator'
      preLoaderRoute: typeof ToolsRoiCalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/ai-readiness-assessment': {
      id: '/tools/ai-readiness-assessment'
      path: '/tools/ai-readiness-assessment'
      fullPath: '/tools/ai-readiness-assessment'
      preLoaderRoute: typeof ToolsAiReadinessAssessmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/digital-transformation': {
      id: '/services/digital-transformation'
      path: '/services/digital-transformation'
      fullPath: '/services/digital-transformation'
      preLoaderRoute: typeof ServicesDigitalTransformationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/chatbots': {
      id: '/services/chatbots'
      path: '/services/chatbots'
      fullPath: '/services/chatbots'
      preLoaderRoute: typeof ServicesChatbotsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/ai-tools': {
      id: '/services/ai-tools'
      path: '/services/ai-tools'
      fullPath: '/services/ai-tools'
      preLoaderRoute: typeof ServicesAiToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/ai-consulting': {
      id: '/services/ai-consulting'
      path: '/services/ai-consulting'
      fullPath: '/services/ai-consulting'
      preLoaderRoute: typeof ServicesAiConsultingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/ai-automation': {
      id: '/services/ai-automation'
      path: '/services/ai-automation'
      fullPath: '/services/ai-automation'
      preLoaderRoute: typeof ServicesAiAutomationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/ai-agents': {
      id: '/services/ai-agents'
      path: '/services/ai-agents'
      fullPath: '/services/ai-agents'
      preLoaderRoute: typeof ServicesAiAgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case-studies/$slug': {
      id: '/case-studies/$slug'
      path: '/case-studies/$slug'
      fullPath: '/case-studies/$slug'
      preLoaderRoute: typeof CaseStudiesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ApproachRoute: ApproachRoute,
  ContactRoute: ContactRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  ResourcesRoute: ResourcesRoute,
  TermsRoute: TermsRoute,
  BlogSlugRoute: BlogSlugRoute,
  CaseStudiesSlugRoute: CaseStudiesSlugRoute,
  ServicesAiAgentsRoute: ServicesAiAgentsRoute,
  ServicesAiAutomationRoute: ServicesAiAutomationRoute,
  ServicesAiConsultingRoute: ServicesAiConsultingRoute,
  ServicesAiToolsRoute: ServicesAiToolsRoute,
  ServicesChatbotsRoute: ServicesChatbotsRoute,
  ServicesDigitalTransformationRoute: ServicesDigitalTransformationRoute,
  ToolsAiReadinessAssessmentRoute: ToolsAiReadinessAssessmentRoute,
  ToolsRoiCalculatorRoute: ToolsRoiCalculatorRoute,
  BlogIndexRoute: BlogIndexRoute,
  CaseStudiesIndexRoute: CaseStudiesIndexRoute,
  ServicesIndexRoute: ServicesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
