/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LocaleRouteImport } from './routes/$locale'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LocaleIndexRouteImport } from './routes/$locale/index'
import { Route as LocaleTermsRouteImport } from './routes/$locale/terms'
import { Route as LocaleResourcesRouteImport } from './routes/$locale/resources'
import { Route as LocalePrivacyPolicyRouteImport } from './routes/$locale/privacy-policy'
import { Route as LocaleContactRouteImport } from './routes/$locale/contact'
import { Route as LocaleApproachRouteImport } from './routes/$locale/approach'
import { Route as LocaleAboutRouteImport } from './routes/$locale/about'
import { Route as LocaleServicesIndexRouteImport } from './routes/$locale/services/index'
import { Route as LocaleCaseStudiesIndexRouteImport } from './routes/$locale/case-studies/index'
import { Route as LocaleBlogIndexRouteImport } from './routes/$locale/blog/index'
import { Route as LocaleToolsRoiCalculatorRouteImport } from './routes/$locale/tools/roi-calculator'
import { Route as LocaleToolsAiReadinessAssessmentRouteImport } from './routes/$locale/tools/ai-readiness-assessment'
import { Route as LocaleServicesDigitalTransformationRouteImport } from './routes/$locale/services/digital-transformation'
import { Route as LocaleServicesChatbotsRouteImport } from './routes/$locale/services/chatbots'
import { Route as LocaleServicesAiToolsRouteImport } from './routes/$locale/services/ai-tools'
import { Route as LocaleServicesAiConsultingRouteImport } from './routes/$locale/services/ai-consulting'
import { Route as LocaleServicesAiAutomationRouteImport } from './routes/$locale/services/ai-automation'
import { Route as LocaleServicesAiAgentsRouteImport } from './routes/$locale/services/ai-agents'
import { Route as LocaleCaseStudiesSlugRouteImport } from './routes/$locale/case-studies/$slug'
import { Route as LocaleBlogSlugRouteImport } from './routes/$locale/blog/$slug'

const LocaleRoute = LocaleRouteImport.update({
  id: '/$locale',
  path: '/$locale',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleIndexRoute = LocaleIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleTermsRoute = LocaleTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleResourcesRoute = LocaleResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => LocaleRoute,
} as any)
const LocalePrivacyPolicyRoute = LocalePrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleContactRoute = LocaleContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleApproachRoute = LocaleApproachRouteImport.update({
  id: '/approach',
  path: '/approach',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleAboutRoute = LocaleAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleServicesIndexRoute = LocaleServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleCaseStudiesIndexRoute = LocaleCaseStudiesIndexRouteImport.update({
  id: '/case-studies/',
  path: '/case-studies/',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleBlogIndexRoute = LocaleBlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleToolsRoiCalculatorRoute =
  LocaleToolsRoiCalculatorRouteImport.update({
    id: '/tools/roi-calculator',
    path: '/tools/roi-calculator',
    getParentRoute: () => LocaleRoute,
  } as any)
const LocaleToolsAiReadinessAssessmentRoute =
  LocaleToolsAiReadinessAssessmentRouteImport.update({
    id: '/tools/ai-readiness-assessment',
    path: '/tools/ai-readiness-assessment',
    getParentRoute: () => LocaleRoute,
  } as any)
const LocaleServicesDigitalTransformationRoute =
  LocaleServicesDigitalTransformationRouteImport.update({
    id: '/services/digital-transformation',
    path: '/services/digital-transformation',
    getParentRoute: () => LocaleRoute,
  } as any)
const LocaleServicesChatbotsRoute = LocaleServicesChatbotsRouteImport.update({
  id: '/services/chatbots',
  path: '/services/chatbots',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleServicesAiToolsRoute = LocaleServicesAiToolsRouteImport.update({
  id: '/services/ai-tools',
  path: '/services/ai-tools',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleServicesAiConsultingRoute =
  LocaleServicesAiConsultingRouteImport.update({
    id: '/services/ai-consulting',
    path: '/services/ai-consulting',
    getParentRoute: () => LocaleRoute,
  } as any)
const LocaleServicesAiAutomationRoute =
  LocaleServicesAiAutomationRouteImport.update({
    id: '/services/ai-automation',
    path: '/services/ai-automation',
    getParentRoute: () => LocaleRoute,
  } as any)
const LocaleServicesAiAgentsRoute = LocaleServicesAiAgentsRouteImport.update({
  id: '/services/ai-agents',
  path: '/services/ai-agents',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleCaseStudiesSlugRoute = LocaleCaseStudiesSlugRouteImport.update({
  id: '/case-studies/$slug',
  path: '/case-studies/$slug',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleBlogSlugRoute = LocaleBlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => LocaleRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$locale': typeof LocaleRouteWithChildren
  '/$locale/about': typeof LocaleAboutRoute
  '/$locale/approach': typeof LocaleApproachRoute
  '/$locale/contact': typeof LocaleContactRoute
  '/$locale/privacy-policy': typeof LocalePrivacyPolicyRoute
  '/$locale/resources': typeof LocaleResourcesRoute
  '/$locale/terms': typeof LocaleTermsRoute
  '/$locale/': typeof LocaleIndexRoute
  '/$locale/blog/$slug': typeof LocaleBlogSlugRoute
  '/$locale/case-studies/$slug': typeof LocaleCaseStudiesSlugRoute
  '/$locale/services/ai-agents': typeof LocaleServicesAiAgentsRoute
  '/$locale/services/ai-automation': typeof LocaleServicesAiAutomationRoute
  '/$locale/services/ai-consulting': typeof LocaleServicesAiConsultingRoute
  '/$locale/services/ai-tools': typeof LocaleServicesAiToolsRoute
  '/$locale/services/chatbots': typeof LocaleServicesChatbotsRoute
  '/$locale/services/digital-transformation': typeof LocaleServicesDigitalTransformationRoute
  '/$locale/tools/ai-readiness-assessment': typeof LocaleToolsAiReadinessAssessmentRoute
  '/$locale/tools/roi-calculator': typeof LocaleToolsRoiCalculatorRoute
  '/$locale/blog/': typeof LocaleBlogIndexRoute
  '/$locale/case-studies/': typeof LocaleCaseStudiesIndexRoute
  '/$locale/services/': typeof LocaleServicesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$locale/about': typeof LocaleAboutRoute
  '/$locale/approach': typeof LocaleApproachRoute
  '/$locale/contact': typeof LocaleContactRoute
  '/$locale/privacy-policy': typeof LocalePrivacyPolicyRoute
  '/$locale/resources': typeof LocaleResourcesRoute
  '/$locale/terms': typeof LocaleTermsRoute
  '/$locale': typeof LocaleIndexRoute
  '/$locale/blog/$slug': typeof LocaleBlogSlugRoute
  '/$locale/case-studies/$slug': typeof LocaleCaseStudiesSlugRoute
  '/$locale/services/ai-agents': typeof LocaleServicesAiAgentsRoute
  '/$locale/services/ai-automation': typeof LocaleServicesAiAutomationRoute
  '/$locale/services/ai-consulting': typeof LocaleServicesAiConsultingRoute
  '/$locale/services/ai-tools': typeof LocaleServicesAiToolsRoute
  '/$locale/services/chatbots': typeof LocaleServicesChatbotsRoute
  '/$locale/services/digital-transformation': typeof LocaleServicesDigitalTransformationRoute
  '/$locale/tools/ai-readiness-assessment': typeof LocaleToolsAiReadinessAssessmentRoute
  '/$locale/tools/roi-calculator': typeof LocaleToolsRoiCalculatorRoute
  '/$locale/blog': typeof LocaleBlogIndexRoute
  '/$locale/case-studies': typeof LocaleCaseStudiesIndexRoute
  '/$locale/services': typeof LocaleServicesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$locale': typeof LocaleRouteWithChildren
  '/$locale/about': typeof LocaleAboutRoute
  '/$locale/approach': typeof LocaleApproachRoute
  '/$locale/contact': typeof LocaleContactRoute
  '/$locale/privacy-policy': typeof LocalePrivacyPolicyRoute
  '/$locale/resources': typeof LocaleResourcesRoute
  '/$locale/terms': typeof LocaleTermsRoute
  '/$locale/': typeof LocaleIndexRoute
  '/$locale/blog/$slug': typeof LocaleBlogSlugRoute
  '/$locale/case-studies/$slug': typeof LocaleCaseStudiesSlugRoute
  '/$locale/services/ai-agents': typeof LocaleServicesAiAgentsRoute
  '/$locale/services/ai-automation': typeof LocaleServicesAiAutomationRoute
  '/$locale/services/ai-consulting': typeof LocaleServicesAiConsultingRoute
  '/$locale/services/ai-tools': typeof LocaleServicesAiToolsRoute
  '/$locale/services/chatbots': typeof LocaleServicesChatbotsRoute
  '/$locale/services/digital-transformation': typeof LocaleServicesDigitalTransformationRoute
  '/$locale/tools/ai-readiness-assessment': typeof LocaleToolsAiReadinessAssessmentRoute
  '/$locale/tools/roi-calculator': typeof LocaleToolsRoiCalculatorRoute
  '/$locale/blog/': typeof LocaleBlogIndexRoute
  '/$locale/case-studies/': typeof LocaleCaseStudiesIndexRoute
  '/$locale/services/': typeof LocaleServicesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$locale'
    | '/$locale/about'
    | '/$locale/approach'
    | '/$locale/contact'
    | '/$locale/privacy-policy'
    | '/$locale/resources'
    | '/$locale/terms'
    | '/$locale/'
    | '/$locale/blog/$slug'
    | '/$locale/case-studies/$slug'
    | '/$locale/services/ai-agents'
    | '/$locale/services/ai-automation'
    | '/$locale/services/ai-consulting'
    | '/$locale/services/ai-tools'
    | '/$locale/services/chatbots'
    | '/$locale/services/digital-transformation'
    | '/$locale/tools/ai-readiness-assessment'
    | '/$locale/tools/roi-calculator'
    | '/$locale/blog/'
    | '/$locale/case-studies/'
    | '/$locale/services/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$locale/about'
    | '/$locale/approach'
    | '/$locale/contact'
    | '/$locale/privacy-policy'
    | '/$locale/resources'
    | '/$locale/terms'
    | '/$locale'
    | '/$locale/blog/$slug'
    | '/$locale/case-studies/$slug'
    | '/$locale/services/ai-agents'
    | '/$locale/services/ai-automation'
    | '/$locale/services/ai-consulting'
    | '/$locale/services/ai-tools'
    | '/$locale/services/chatbots'
    | '/$locale/services/digital-transformation'
    | '/$locale/tools/ai-readiness-assessment'
    | '/$locale/tools/roi-calculator'
    | '/$locale/blog'
    | '/$locale/case-studies'
    | '/$locale/services'
  id:
    | '__root__'
    | '/'
    | '/$locale'
    | '/$locale/about'
    | '/$locale/approach'
    | '/$locale/contact'
    | '/$locale/privacy-policy'
    | '/$locale/resources'
    | '/$locale/terms'
    | '/$locale/'
    | '/$locale/blog/$slug'
    | '/$locale/case-studies/$slug'
    | '/$locale/services/ai-agents'
    | '/$locale/services/ai-automation'
    | '/$locale/services/ai-consulting'
    | '/$locale/services/ai-tools'
    | '/$locale/services/chatbots'
    | '/$locale/services/digital-transformation'
    | '/$locale/tools/ai-readiness-assessment'
    | '/$locale/tools/roi-calculator'
    | '/$locale/blog/'
    | '/$locale/case-studies/'
    | '/$locale/services/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LocaleRoute: typeof LocaleRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$locale': {
      id: '/$locale'
      path: '/$locale'
      fullPath: '/$locale'
      preLoaderRoute: typeof LocaleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/': {
      id: '/$locale/'
      path: '/'
      fullPath: '/$locale/'
      preLoaderRoute: typeof LocaleIndexRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/terms': {
      id: '/$locale/terms'
      path: '/terms'
      fullPath: '/$locale/terms'
      preLoaderRoute: typeof LocaleTermsRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/resources': {
      id: '/$locale/resources'
      path: '/resources'
      fullPath: '/$locale/resources'
      preLoaderRoute: typeof LocaleResourcesRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/privacy-policy': {
      id: '/$locale/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/$locale/privacy-policy'
      preLoaderRoute: typeof LocalePrivacyPolicyRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/contact': {
      id: '/$locale/contact'
      path: '/contact'
      fullPath: '/$locale/contact'
      preLoaderRoute: typeof LocaleContactRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/approach': {
      id: '/$locale/approach'
      path: '/approach'
      fullPath: '/$locale/approach'
      preLoaderRoute: typeof LocaleApproachRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/about': {
      id: '/$locale/about'
      path: '/about'
      fullPath: '/$locale/about'
      preLoaderRoute: typeof LocaleAboutRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/services/': {
      id: '/$locale/services/'
      path: '/services'
      fullPath: '/$locale/services/'
      preLoaderRoute: typeof LocaleServicesIndexRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/case-studies/': {
      id: '/$locale/case-studies/'
      path: '/case-studies'
      fullPath: '/$locale/case-studies/'
      preLoaderRoute: typeof LocaleCaseStudiesIndexRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/blog/': {
      id: '/$locale/blog/'
      path: '/blog'
      fullPath: '/$locale/blog/'
      preLoaderRoute: typeof LocaleBlogIndexRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/tools/roi-calculator': {
      id: '/$locale/tools/roi-calculator'
      path: '/tools/roi-calculator'
      fullPath: '/$locale/tools/roi-calculator'
      preLoaderRoute: typeof LocaleToolsRoiCalculatorRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/tools/ai-readiness-assessment': {
      id: '/$locale/tools/ai-readiness-assessment'
      path: '/tools/ai-readiness-assessment'
      fullPath: '/$locale/tools/ai-readiness-assessment'
      preLoaderRoute: typeof LocaleToolsAiReadinessAssessmentRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/services/digital-transformation': {
      id: '/$locale/services/digital-transformation'
      path: '/services/digital-transformation'
      fullPath: '/$locale/services/digital-transformation'
      preLoaderRoute: typeof LocaleServicesDigitalTransformationRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/services/chatbots': {
      id: '/$locale/services/chatbots'
      path: '/services/chatbots'
      fullPath: '/$locale/services/chatbots'
      preLoaderRoute: typeof LocaleServicesChatbotsRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/services/ai-tools': {
      id: '/$locale/services/ai-tools'
      path: '/services/ai-tools'
      fullPath: '/$locale/services/ai-tools'
      preLoaderRoute: typeof LocaleServicesAiToolsRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/services/ai-consulting': {
      id: '/$locale/services/ai-consulting'
      path: '/services/ai-consulting'
      fullPath: '/$locale/services/ai-consulting'
      preLoaderRoute: typeof LocaleServicesAiConsultingRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/services/ai-automation': {
      id: '/$locale/services/ai-automation'
      path: '/services/ai-automation'
      fullPath: '/$locale/services/ai-automation'
      preLoaderRoute: typeof LocaleServicesAiAutomationRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/services/ai-agents': {
      id: '/$locale/services/ai-agents'
      path: '/services/ai-agents'
      fullPath: '/$locale/services/ai-agents'
      preLoaderRoute: typeof LocaleServicesAiAgentsRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/case-studies/$slug': {
      id: '/$locale/case-studies/$slug'
      path: '/case-studies/$slug'
      fullPath: '/$locale/case-studies/$slug'
      preLoaderRoute: typeof LocaleCaseStudiesSlugRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/blog/$slug': {
      id: '/$locale/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/$locale/blog/$slug'
      preLoaderRoute: typeof LocaleBlogSlugRouteImport
      parentRoute: typeof LocaleRoute
    }
  }
}

interface LocaleRouteChildren {
  LocaleAboutRoute: typeof LocaleAboutRoute
  LocaleApproachRoute: typeof LocaleApproachRoute
  LocaleContactRoute: typeof LocaleContactRoute
  LocalePrivacyPolicyRoute: typeof LocalePrivacyPolicyRoute
  LocaleResourcesRoute: typeof LocaleResourcesRoute
  LocaleTermsRoute: typeof LocaleTermsRoute
  LocaleIndexRoute: typeof LocaleIndexRoute
  LocaleBlogSlugRoute: typeof LocaleBlogSlugRoute
  LocaleCaseStudiesSlugRoute: typeof LocaleCaseStudiesSlugRoute
  LocaleServicesAiAgentsRoute: typeof LocaleServicesAiAgentsRoute
  LocaleServicesAiAutomationRoute: typeof LocaleServicesAiAutomationRoute
  LocaleServicesAiConsultingRoute: typeof LocaleServicesAiConsultingRoute
  LocaleServicesAiToolsRoute: typeof LocaleServicesAiToolsRoute
  LocaleServicesChatbotsRoute: typeof LocaleServicesChatbotsRoute
  LocaleServicesDigitalTransformationRoute: typeof LocaleServicesDigitalTransformationRoute
  LocaleToolsAiReadinessAssessmentRoute: typeof LocaleToolsAiReadinessAssessmentRoute
  LocaleToolsRoiCalculatorRoute: typeof LocaleToolsRoiCalculatorRoute
  LocaleBlogIndexRoute: typeof LocaleBlogIndexRoute
  LocaleCaseStudiesIndexRoute: typeof LocaleCaseStudiesIndexRoute
  LocaleServicesIndexRoute: typeof LocaleServicesIndexRoute
}

const LocaleRouteChildren: LocaleRouteChildren = {
  LocaleAboutRoute: LocaleAboutRoute,
  LocaleApproachRoute: LocaleApproachRoute,
  LocaleContactRoute: LocaleContactRoute,
  LocalePrivacyPolicyRoute: LocalePrivacyPolicyRoute,
  LocaleResourcesRoute: LocaleResourcesRoute,
  LocaleTermsRoute: LocaleTermsRoute,
  LocaleIndexRoute: LocaleIndexRoute,
  LocaleBlogSlugRoute: LocaleBlogSlugRoute,
  LocaleCaseStudiesSlugRoute: LocaleCaseStudiesSlugRoute,
  LocaleServicesAiAgentsRoute: LocaleServicesAiAgentsRoute,
  LocaleServicesAiAutomationRoute: LocaleServicesAiAutomationRoute,
  LocaleServicesAiConsultingRoute: LocaleServicesAiConsultingRoute,
  LocaleServicesAiToolsRoute: LocaleServicesAiToolsRoute,
  LocaleServicesChatbotsRoute: LocaleServicesChatbotsRoute,
  LocaleServicesDigitalTransformationRoute:
    LocaleServicesDigitalTransformationRoute,
  LocaleToolsAiReadinessAssessmentRoute: LocaleToolsAiReadinessAssessmentRoute,
  LocaleToolsRoiCalculatorRoute: LocaleToolsRoiCalculatorRoute,
  LocaleBlogIndexRoute: LocaleBlogIndexRoute,
  LocaleCaseStudiesIndexRoute: LocaleCaseStudiesIndexRoute,
  LocaleServicesIndexRoute: LocaleServicesIndexRoute,
}

const LocaleRouteWithChildren =
  LocaleRoute._addFileChildren(LocaleRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LocaleRoute: LocaleRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
