/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ApproachRouteImport } from './routes/approach'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesIndexRouteImport } from './routes/services/index'
import { Route as ServicesDigitalTransformationRouteImport } from './routes/services/digital-transformation'
import { Route as ServicesChatbotsRouteImport } from './routes/services/chatbots'
import { Route as ServicesAiToolsRouteImport } from './routes/services/ai-tools'
import { Route as ServicesAiConsultingRouteImport } from './routes/services/ai-consulting'
import { Route as ServicesAiAutomationRouteImport } from './routes/services/ai-automation'
import { Route as ServicesAiAgentsRouteImport } from './routes/services/ai-agents'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ApproachRoute = ApproachRouteImport.update({
  id: '/approach',
  path: '/approach',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesDigitalTransformationRoute =
  ServicesDigitalTransformationRouteImport.update({
    id: '/services/digital-transformation',
    path: '/services/digital-transformation',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesChatbotsRoute = ServicesChatbotsRouteImport.update({
  id: '/services/chatbots',
  path: '/services/chatbots',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesAiToolsRoute = ServicesAiToolsRouteImport.update({
  id: '/services/ai-tools',
  path: '/services/ai-tools',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesAiConsultingRoute = ServicesAiConsultingRouteImport.update({
  id: '/services/ai-consulting',
  path: '/services/ai-consulting',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesAiAutomationRoute = ServicesAiAutomationRouteImport.update({
  id: '/services/ai-automation',
  path: '/services/ai-automation',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesAiAgentsRoute = ServicesAiAgentsRouteImport.update({
  id: '/services/ai-agents',
  path: '/services/ai-agents',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/approach': typeof ApproachRoute
  '/contact': typeof ContactRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/terms': typeof TermsRoute
  '/services/ai-agents': typeof ServicesAiAgentsRoute
  '/services/ai-automation': typeof ServicesAiAutomationRoute
  '/services/ai-consulting': typeof ServicesAiConsultingRoute
  '/services/ai-tools': typeof ServicesAiToolsRoute
  '/services/chatbots': typeof ServicesChatbotsRoute
  '/services/digital-transformation': typeof ServicesDigitalTransformationRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/approach': typeof ApproachRoute
  '/contact': typeof ContactRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/terms': typeof TermsRoute
  '/services/ai-agents': typeof ServicesAiAgentsRoute
  '/services/ai-automation': typeof ServicesAiAutomationRoute
  '/services/ai-consulting': typeof ServicesAiConsultingRoute
  '/services/ai-tools': typeof ServicesAiToolsRoute
  '/services/chatbots': typeof ServicesChatbotsRoute
  '/services/digital-transformation': typeof ServicesDigitalTransformationRoute
  '/services': typeof ServicesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/approach': typeof ApproachRoute
  '/contact': typeof ContactRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/terms': typeof TermsRoute
  '/services/ai-agents': typeof ServicesAiAgentsRoute
  '/services/ai-automation': typeof ServicesAiAutomationRoute
  '/services/ai-consulting': typeof ServicesAiConsultingRoute
  '/services/ai-tools': typeof ServicesAiToolsRoute
  '/services/chatbots': typeof ServicesChatbotsRoute
  '/services/digital-transformation': typeof ServicesDigitalTransformationRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/approach'
    | '/contact'
    | '/privacy-policy'
    | '/terms'
    | '/services/ai-agents'
    | '/services/ai-automation'
    | '/services/ai-consulting'
    | '/services/ai-tools'
    | '/services/chatbots'
    | '/services/digital-transformation'
    | '/services/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/approach'
    | '/contact'
    | '/privacy-policy'
    | '/terms'
    | '/services/ai-agents'
    | '/services/ai-automation'
    | '/services/ai-consulting'
    | '/services/ai-tools'
    | '/services/chatbots'
    | '/services/digital-transformation'
    | '/services'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/approach'
    | '/contact'
    | '/privacy-policy'
    | '/terms'
    | '/services/ai-agents'
    | '/services/ai-automation'
    | '/services/ai-consulting'
    | '/services/ai-tools'
    | '/services/chatbots'
    | '/services/digital-transformation'
    | '/services/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ApproachRoute: typeof ApproachRoute
  ContactRoute: typeof ContactRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  TermsRoute: typeof TermsRoute
  ServicesAiAgentsRoute: typeof ServicesAiAgentsRoute
  ServicesAiAutomationRoute: typeof ServicesAiAutomationRoute
  ServicesAiConsultingRoute: typeof ServicesAiConsultingRoute
  ServicesAiToolsRoute: typeof ServicesAiToolsRoute
  ServicesChatbotsRoute: typeof ServicesChatbotsRoute
  ServicesDigitalTransformationRoute: typeof ServicesDigitalTransformationRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/approach': {
      id: '/approach'
      path: '/approach'
      fullPath: '/approach'
      preLoaderRoute: typeof ApproachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/digital-transformation': {
      id: '/services/digital-transformation'
      path: '/services/digital-transformation'
      fullPath: '/services/digital-transformation'
      preLoaderRoute: typeof ServicesDigitalTransformationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/chatbots': {
      id: '/services/chatbots'
      path: '/services/chatbots'
      fullPath: '/services/chatbots'
      preLoaderRoute: typeof ServicesChatbotsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/ai-tools': {
      id: '/services/ai-tools'
      path: '/services/ai-tools'
      fullPath: '/services/ai-tools'
      preLoaderRoute: typeof ServicesAiToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/ai-consulting': {
      id: '/services/ai-consulting'
      path: '/services/ai-consulting'
      fullPath: '/services/ai-consulting'
      preLoaderRoute: typeof ServicesAiConsultingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/ai-automation': {
      id: '/services/ai-automation'
      path: '/services/ai-automation'
      fullPath: '/services/ai-automation'
      preLoaderRoute: typeof ServicesAiAutomationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/ai-agents': {
      id: '/services/ai-agents'
      path: '/services/ai-agents'
      fullPath: '/services/ai-agents'
      preLoaderRoute: typeof ServicesAiAgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ApproachRoute: ApproachRoute,
  ContactRoute: ContactRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  TermsRoute: TermsRoute,
  ServicesAiAgentsRoute: ServicesAiAgentsRoute,
  ServicesAiAutomationRoute: ServicesAiAutomationRoute,
  ServicesAiConsultingRoute: ServicesAiConsultingRoute,
  ServicesAiToolsRoute: ServicesAiToolsRoute,
  ServicesChatbotsRoute: ServicesChatbotsRoute,
  ServicesDigitalTransformationRoute: ServicesDigitalTransformationRoute,
  ServicesIndexRoute: ServicesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
